/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreJogoRouteImport } from './routes/sobre-jogo'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ScoresRouteImport } from './routes/scores'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as GameRouteImport } from './routes/game'
import { Route as CreditosRouteImport } from './routes/creditos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'

const SobreJogoRoute = SobreJogoRouteImport.update({
  id: '/sobre-jogo',
  path: '/sobre-jogo',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoresRoute = ScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditosRoute = CreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/creditos': typeof CreditosRoute
  '/game': typeof GameRoute
  '/privacidade': typeof PrivacidadeRoute
  '/ranking': typeof RankingRoute
  '/scores': typeof ScoresRoute
  '/sobre': typeof SobreRoute
  '/sobre-jogo': typeof SobreJogoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/creditos': typeof CreditosRoute
  '/game': typeof GameRoute
  '/privacidade': typeof PrivacidadeRoute
  '/ranking': typeof RankingRoute
  '/scores': typeof ScoresRoute
  '/sobre': typeof SobreRoute
  '/sobre-jogo': typeof SobreJogoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/creditos': typeof CreditosRoute
  '/game': typeof GameRoute
  '/privacidade': typeof PrivacidadeRoute
  '/ranking': typeof RankingRoute
  '/scores': typeof ScoresRoute
  '/sobre': typeof SobreRoute
  '/sobre-jogo': typeof SobreJogoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/creditos'
    | '/game'
    | '/privacidade'
    | '/ranking'
    | '/scores'
    | '/sobre'
    | '/sobre-jogo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/creditos'
    | '/game'
    | '/privacidade'
    | '/ranking'
    | '/scores'
    | '/sobre'
    | '/sobre-jogo'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/creditos'
    | '/game'
    | '/privacidade'
    | '/ranking'
    | '/scores'
    | '/sobre'
    | '/sobre-jogo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CreditosRoute: typeof CreditosRoute
  GameRoute: typeof GameRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RankingRoute: typeof RankingRoute
  ScoresRoute: typeof ScoresRoute
  SobreRoute: typeof SobreRoute
  SobreJogoRoute: typeof SobreJogoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-jogo': {
      id: '/sobre-jogo'
      path: '/sobre-jogo'
      fullPath: '/sobre-jogo'
      preLoaderRoute: typeof SobreJogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores': {
      id: '/scores'
      path: '/scores'
      fullPath: '/scores'
      preLoaderRoute: typeof ScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creditos': {
      id: '/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof CreditosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CreditosRoute: CreditosRoute,
  GameRoute: GameRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RankingRoute: RankingRoute,
  ScoresRoute: ScoresRoute,
  SobreRoute: SobreRoute,
  SobreJogoRoute: SobreJogoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
